import 'dart:async';
import 'dart:io';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:supabase_flutter/supabase_flutter.dart';
import '../data/portfolio_repository.dart';
import '../domain/portfolio_project.dart';
import '../domain/service_package.dart';

// --- Portfolio Projects Controller ---
class DesignerProjectsController extends AsyncNotifier<List<PortfolioProject>> {
  late PortfolioRepository _repository;

  @override
  FutureOr<List<PortfolioProject>> build() async {
    _repository = ref.watch(portfolioRepositoryProvider);
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return [];
    return await _repository.getProjects(user.id);
  }

  Future<bool> addProject({
    required String title,
    required String description,
    required List<File> imageFiles,
    required List<String> styleTags,
    required double pricing,
    required String projectType,
    required String completionTime,
  }) async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return false;

    state = const AsyncLoading();
    try {
      final List<String> imageUrls = [];
      for (final file in imageFiles) {
        final url = await _repository.uploadImage(file, 'portfolio');
        imageUrls.add(url);
      }

      // If no image files uploaded, add a premium default interior render URL
      if (imageUrls.isEmpty) {
        imageUrls.add('https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop');
      }

      final project = PortfolioProject(
        id: '', // Will be generated by DB
        designerId: user.id,
        title: title,
        description: description,
        images: imageUrls,
        styleTags: styleTags,
        pricing: pricing,
        projectType: projectType,
        completionTime: completionTime,
        createdAt: DateTime.now(),
      );

      await _repository.addProject(project);
      
      // Refresh list
      final refreshed = await _repository.getProjects(user.id);
      state = AsyncData(refreshed);
      return true;
    } catch (e, st) {
      state = AsyncError(e, st);
      return false;
    }
  }

  Future<bool> updateProject({
    required String projectId,
    required String title,
    required String description,
    required List<String> existingImages,
    required List<File> newImageFiles,
    required List<String> styleTags,
    required double pricing,
    required String projectType,
    required String completionTime,
  }) async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return false;

    state = const AsyncLoading();
    try {
      final List<String> imageUrls = [...existingImages];
      for (final file in newImageFiles) {
        final url = await _repository.uploadImage(file, 'portfolio');
        imageUrls.add(url);
      }

      if (imageUrls.isEmpty) {
        imageUrls.add('https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop');
      }

      final project = PortfolioProject(
        id: projectId,
        designerId: user.id,
        title: title,
        description: description,
        images: imageUrls,
        styleTags: styleTags,
        pricing: pricing,
        projectType: projectType,
        completionTime: completionTime,
        createdAt: DateTime.now(),
      );

      await _repository.updateProject(project);

      // Refresh list
      final refreshed = await _repository.getProjects(user.id);
      state = AsyncData(refreshed);
      return true;
    } catch (e, st) {
      state = AsyncError(e, st);
      return false;
    }
  }

  Future<bool> deleteProject(String projectId) async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return false;

    state = const AsyncLoading();
    try {
      await _repository.deleteProject(projectId);
      final refreshed = await _repository.getProjects(user.id);
      state = AsyncData(refreshed);
      return true;
    } catch (e, st) {
      state = AsyncError(e, st);
      return false;
    }
  }
}

final designerProjectsProvider =
    AsyncNotifierProvider<DesignerProjectsController, List<PortfolioProject>>(() {
  return DesignerProjectsController();
});

// --- Service Packages Controller ---
class DesignerPackagesController extends AsyncNotifier<List<ServicePackage>> {
  late PortfolioRepository _repository;

  @override
  FutureOr<List<ServicePackage>> build() async {
    _repository = ref.watch(portfolioRepositoryProvider);
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return [];
    return await _repository.getPackages(user.id);
  }

  Future<bool> savePackage({
    String? id,
    required String name,
    required String description,
    required double price,
    required List<String> features,
  }) async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return false;

    state = const AsyncLoading();
    try {
      final package = ServicePackage(
        id: id ?? '',
        designerId: user.id,
        name: name,
        description: description,
        price: price,
        features: features,
        createdAt: DateTime.now(),
      );

      await _repository.savePackage(package);
      final refreshed = await _repository.getPackages(user.id);
      state = AsyncData(refreshed);
      return true;
    } catch (e, st) {
      state = AsyncError(e, st);
      return false;
    }
  }

  Future<bool> deletePackage(String packageId) async {
    final user = Supabase.instance.client.auth.currentUser;
    if (user == null) return false;

    state = const AsyncLoading();
    try {
      await _repository.deletePackage(packageId);
      final refreshed = await _repository.getPackages(user.id);
      state = AsyncData(refreshed);
      return true;
    } catch (e, st) {
      state = AsyncError(e, st);
      return false;
    }
  }
}

final designerPackagesProvider =
    AsyncNotifierProvider<DesignerPackagesController, List<ServicePackage>>(() {
  return DesignerPackagesController();
});
